version: '3.5'
services:
   database:
     image: dbmaria
     container_name: dbmaria
     command: ["mysqld","--character-set-server=utf8","--collation-server=utf8_bin"]
     ports:
     - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD:db.env
     volumes:
       - db_data:/var/lib/mysql
      
   webserver:
     depends_on:
       - database
     image: apptpass
     container_name: apptpass
     command: ["apachectl", "-D FOREGROUND"] 
     ports:
       - "80:80"
     volumes:
       - ./teampass/:/var/www/html/teampass
     
networks:
- netpass
volumes:
    db_data: {}
