version: '3.5'
services:
   database:
     image: mariadb/server
     container_name: dbmaria
     command: ["mysqld","--character-set-server=utf8","--collation-server=utf8_bin"]
     ports:
       - "3306:3306"
     environment:
       - MARIADB_ROOT_PASSWORD= testeteste
     volumes:
       - db_data:/var/lib/mysql
      
   webserver:
     depends_on:
             - database
     image: apptpass
     container_name: apptpass
     ports:
       - "80:80"
     volumes:
       - ./teampass/:/var/www/html/teampass
     
volumes:
    db_data: {}
