version: '3.5'
services:
webserver:
image: appteam
container_name: appteam
command: ["apachectl", "-D FOREGROUND"] 
ports:
- "80:80"
volumes:
- ./teampass/:/var/www/html/teampass
depends_on:
- database
networks:
- netpass
links:
- "database:dbmaria"
database:
image: dbmaria
container_name: dbmaria
command: ["mysqld","--character-set-server=utf8","--collation-server=utf8_bin"]
ports:
- "3306:3306"
environment:
- MYSQL_ROOT_PASSWORD:db.env
volumes:
- ./teampass/db:/var/lib/mysql
networks:
- netpass
networks:
netpass:
